version: '{build}'
clone_depth: 10
environment:
  matrix:
    - VIM: kaoriya
      VIM_VERSION: 7.4
      VIM_ARCH: 32
      THEMIS_PROFILE: kaoriya-vim-profile-win-v7.4-32.txt
    - VIM: kaoriya
      VIM_VERSION: 7.4
      VIM_ARCH: 64
      THEMIS_PROFILE: kaoriya-vim-profile-win-v7.4-64.txt
    - VIM: kaoriya
      VIM_VERSION: 8.0
      VIM_ARCH: 32
      THEMIS_PROFILE: kaoriya-vim-profile-win-v8.0-32.txt
    - VIM: kaoriya
      VIM_VERSION: 8.0
      VIM_ARCH: 64
      THEMIS_PROFILE: kaoriya-vim-profile-win-v8.0-64.txt
    - VIM: kaoriya
      VIM_VERSION: latest
      VIM_ARCH: 32
      THEMIS_PROFILE: kaoriya-vim-profile-win-latest-32.txt
    - VIM: kaoriya
      VIM_VERSION: latest
      VIM_ARCH: 64
      THEMIS_PROFILE: kaoriya-vim-profile-win-latest-64.txt
    # lua53.dll could not be loaded somehow
    # - VIM: vim
    #   VIM_VERSION: 8.0.0027
    #   VIM_ARCH: x86
    #   THEMIS_PROFILE: vim-profile-win-8.0.0027-32.txt
    - VIM: vim
      VIM_VERSION: 8.0.0027
      VIM_ARCH: x64
      THEMIS_PROFILE: vim-profile-win-8.0.0027-64.txt
    # lua53.dll could not be loaded somehow
    # - VIM: vim
    #   VIM_VERSION: latest
    #   VIM_ARCH: x86
    #   THEMIS_PROFILE: vim-profile-win-latest-32.txt
    - VIM: vim
      VIM_VERSION: latest
      VIM_ARCH: x64
      THEMIS_PROFILE: vim-profile-win-latest-64.txt
    - VIM: nvim
      VIM_VERSION: 0.2.0
      VIM_ARCH: 32
      THEMIS_PROFILE: neovim-profile-win-0.2.0-32.txt
    - VIM: nvim
      VIM_VERSION: 0.2.0
      VIM_ARCH: 64
      THEMIS_PROFILE: neovim-profile-win-0.2.0-64.txt
    - VIM: nvim
      VIM_VERSION: 0.2.2
      VIM_ARCH: 32
      THEMIS_PROFILE: neovim-profile-win-0.2.2-32.txt
    - VIM: nvim
      VIM_VERSION: 0.2.2
      VIM_ARCH: 64
      THEMIS_PROFILE: neovim-profile-win-0.2.2-64.txt
    - VIM: nvim
      VIM_VERSION: latest
      VIM_ARCH: 32
      THEMIS_PROFILE: neovim-profile-win-latest-32.txt
    - VIM: nvim
      VIM_VERSION: latest
      VIM_ARCH: 64
      THEMIS_PROFILE: neovim-profile-win-latest-64.txt
install:
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64'
  - 'git config --global user.name "Appveyor"'
  - 'git config --global user.email appveyor@example.com'
  - 'git clone -q --depth 1 --single-branch --branch v1.5.4 https://github.com/thinca/vim-themis %TEMP%\vim-themis'
  - 'git clone -q --depth 1 --single-branch --branch ver.9.2 https://github.com/Shougo/vimproc.vim %TEMP%\vimproc'
  - 'appveyor DownloadFile https://github.com/Shougo/vimproc.vim/releases/download/ver.9.2/vimproc_win64.dll -FileName %TEMP%\vimproc\lib\vimproc_win64.dll'
  - 'choco install lua53'
  - 'set THEMIS_HOME=%TEMP%\vim-themis'
  - 'set PATH=%ProgramData%\chocolatey\lib\lua53\tools;%THEMIS_HOME%\bin;%PATH%'
  - ps: scripts/install.windows.ps1


test_script:
  - 'echo %PATH%'
  - 'echo %THEMIS_HOME%'
  - 'echo %THEMIS_VIM%'
  - 'echo %THEMIS_ARGS%'
  - '%THEMIS_VIM% --version'
  - 'themis --version'
  - 'themis --reporter dot --runtimepath %TEMP%\vimproc --exclude ConcurrentProcess'

after_test:
  - 'set PATH=C:\Python34;C:\Python34\Scripts;%PATH%'
  - pip install codecov
  - pip install covimerage
  - covimerage write_coverage %THEMIS_PROFILE%
  - coverage xml
  - codecov -f coverage.xml

notifications:
  - provider: Webhook
    url: http://appveyor.herokuapp.com/vim
    headers:
      User-Agent: appveyor-lingrbot 1.0
      Authorization:
        secure: cjzTMN7bP3fkRnz6S0ZRjc0Q3nPPvdJ7AXrizCQBKK0=
    on_build_success: false
    on_build_failure: true

build: off
deploy: off
