# Run the below command when you edit .drone.yml
#   drone secure --repo vim-jp/vital.vim --in .drone.sec.yaml
#
build:
  lint:
    image: haya14busa/lint-vital.vim:0.9.3
    environment:
      - REVIEWDOG_GITHUB_API_TOKEN=$$REVIEWDOG_GITHUB_API_TOKEN
    commands:
      - reviewdog -ci=droneio
    when:
      event: pull_request
