version: 2
workflows:
  version: 2
  test:
    jobs:
      - v8.0.0000
      - v8.1.0005
      - latest

_test-body: &test-body
 working_directory: ~/repo
 steps:
   - checkout
   - run: git clone --depth 1 --branch v1.5.4 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis
   - run: git clone --depth 1 https://github.com/Shougo/vimproc.vim /tmp/vimproc
   - run: (cd /tmp/vimproc && make)
   - run: LANG=ja_JP.UTF-8 /tmp/vim-themis/bin/themis --runtimepath /tmp/vimproc --exclude ConcurrentProcess --reporter dot

jobs:
  v8.0.0000:
    docker:
      - image: thinca/vim:v8.0.0000
  v8.1.0005:
    docker:
      - image: thinca/vim:v8.1.0005
  latest:
    docker:
      - image: thinca/vim:latest
